version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install ruby-full
      - run: ruby -v
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  build:
    jobs:
      - build-and-test
