version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install ruby-full python3-pip
      - run: ruby -v
      - run: python3 --version
      - run: pip3 --version
      - run: pip3 install pre-commit==2.21.0
      - run: pre-commit run --all-files
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  build:
    jobs:
      - build-and-test
