version: 2.1
docker:
    - image: cimg/openjdk:11.0
environment:
    PRE_COMMIT_RUN_ALL_FILES: false

jobs:
  setup-and-checkout:
    - checkout
    - run: sudo apt update
    - run: sudo apt install ruby-full python3-pip
    - run: ruby -v
    - run: python3 --version
    - run: pip3 --version
    - run: pip3 install pre-commit==2.21.0
  lint:
    - run: if $PRE_COMMIT_RUN_ALL_FILES; then pre-commit run --all-files; else pre-commit run --from-ref origin/HEAD --to-ref HEAD; fi
  build-and-test:
    steps:
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  build:
    jobs:
      - setup-and-checkout
      - lint:
          requires: setup-and-checkout
          when: on_fail #allow to fail
      - build-and-test:
          requires: lint
